proxy:
  build: nginx
  volumes:
   - /etc/nginx/conf.d
   - /usr/share/nginx/html
  ports:
    - "8002:80"
  cap_drop:
   - ALL
  cap_add:
   - SETUID
   - SETGID
   - CHOWN
   - KILL
   - NET_BIND_SERVICE

updater:
  build: .
  cap_drop:
     - ALL
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - proxy

