proxy:
  build: nginx
  volumes:
   - /etc/nginx/conf.d
   - /usr/share/nginx/html
  ports:
    - "8002:80"

updater:
  build: .
  cap_drop:
     - ALL
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - proxy

